// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDudRhqWWdUeZIlOHriL6SJKOaPwbY6y2c',
    appId: '1:24498551647:web:75cdc59a006b9ca8a694ea',
    messagingSenderId: '24498551647',
    projectId: 'adv-flutter-bc08d',
    authDomain: 'adv-flutter-bc08d.firebaseapp.com',
    storageBucket: 'adv-flutter-bc08d.firebasestorage.app',
    measurementId: 'G-ZWNLBBDWFS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrdQaRlMsCKRSNQntXAgQ2wuTHTDnCr1g',
    appId: '1:24498551647:android:de02ffba49d3f98da694ea',
    messagingSenderId: '24498551647',
    projectId: 'adv-flutter-bc08d',
    storageBucket: 'adv-flutter-bc08d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKtgdoBNkviIh7D1UJfHCZ7Y0fuH8Rn54',
    appId: '1:24498551647:ios:c4347be482a77e4da694ea',
    messagingSenderId: '24498551647',
    projectId: 'adv-flutter-bc08d',
    storageBucket: 'adv-flutter-bc08d.firebasestorage.app',
    iosClientId: '24498551647-s93modgbvm216ao08am6je24v6umt68d.apps.googleusercontent.com',
    iosBundleId: 'com.example.advFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKtgdoBNkviIh7D1UJfHCZ7Y0fuH8Rn54',
    appId: '1:24498551647:ios:c4347be482a77e4da694ea',
    messagingSenderId: '24498551647',
    projectId: 'adv-flutter-bc08d',
    storageBucket: 'adv-flutter-bc08d.firebasestorage.app',
    iosClientId: '24498551647-s93modgbvm216ao08am6je24v6umt68d.apps.googleusercontent.com',
    iosBundleId: 'com.example.advFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDudRhqWWdUeZIlOHriL6SJKOaPwbY6y2c',
    appId: '1:24498551647:web:be145b3c930164c7a694ea',
    messagingSenderId: '24498551647',
    projectId: 'adv-flutter-bc08d',
    authDomain: 'adv-flutter-bc08d.firebaseapp.com',
    storageBucket: 'adv-flutter-bc08d.firebasestorage.app',
    measurementId: 'G-WL7MM88G11',
  );

}